# Generated by Django 5.2 on 2025-05-30 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='mgr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='app.emp'),
        ),
        migrations.AlterField(
            model_name='sal',
            name='Grade',
            field=models.IntegerField(),
        ),
    ]
