# Generated by Django 5.2 on 2025-05-30 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_emp_mgr_alter_sal_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='mgr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.emp'),
        ),
    ]
